### ISSUE TITLE
Usage with Typescript

### ISSUE THREAD

**Issue by bm-software** [onemolegames/react-native-toast-native#16]
I have a react-native project with typoescript.
How could I use you library with it? I've already tried the  `require` but it doesn't work. I've tried to define typings too (see below) but it doesn't work.

    declare module 'react-native-toast-native' {
        export class Toast {
            private constructor();
    
            show(): void
            show(message: string): void
            show(message: string, duration: RNToast.android.Duration | RNToast.ios.Duration, position: RNToast.android.Position | RNToast.ios.Position, styles: RNToast.Style): void
        }
    
        const toast: Toast;
        export default toast;
    
        export namespace RNToast {
            namespace android {
                enum Duration {
                    SHORT = 0,
                    LONG = 1
                }
                enum Position {
                    BOTTOM = 80,            
                    CENTER = 17,
                    TOP = 48
                }
            }
    
            namespace ios {
                enum Duration {
                    SHORT = 3,
                    LONG = 5
                }
                enum Position {
                    BOTTOM = 1,
                    CENTER = 2,
                    TOP = 3
                }
            }
    
            interface Style {
                width?: number,
                height?: number,
                backgroundColor?: string,
                color?: string,
                borderWidth?: number,
                borderRadius?: number,
        
                // iOS-only
                borderColor?: string,
        
                // Android-only
                paddingLeft?: number,
                paddingRight?: number,
                paddingBottom?: number,
                paddingTop?: number,
                fontSize?: number,
                lines?: number,
                lineHeight?: number,
                xOffset?: number,
                yOffset?: number,
                letterSpacing?: number,
                fontWeight?: string
            }
        }
    }

Could you help me?

*EDIT*
Ok with

`import Toast from 'react-native-toast-native';`

it works but vs code give me an error because the module could not be found. Maybe, could you add typings to you project? :)

**Comment by yasemincidem** [comment]
Actually i don't think this problem is related to types. Maybe you have a problem about linting. Can you make sure linting correctly ?

**Comment by bm-software** [comment]
@yasemincidem Finally I've made it works.
I've implemented these typings:

    declare module 'react-native-toast-native' {
        //Toast duration constants
        var SHORT
        var LONG
    
        // Toast gravity constants
        var TOP
        var BOTTOM
        var CENTER
    
        export function show(): void
        export function show(message: string): void
        export function show(message: string, duration: any, position: any, styles: Style): void
    
        interface Style {
            width?: number,
            height?: number,
            backgroundColor?: string,
            color?: string,
            borderWidth?: number,
            borderRadius?: number,
    
            // iOS-only
            borderColor?: string,
    
            // Android-only
            paddingLeft?: number,
            paddingRight?: number,
            paddingBottom?: number,
            paddingTop?: number,
            fontSize?: number,
            lines?: number,
            lineHeight?: number,
            xOffset?: number,
            yOffset?: number,
            letterSpacing?: number,
            fontWeight?: string
        }
    }

Along with the following helper class:

    import { Platform } from 'react-native'
    import { deepCopy } from '../utils'
    import colors from '../ui/colors'
    
    import Toast, { Style } from 'react-native-toast-native';
    
    // TODO configure on iOS https://github.com/onemolegames/react-native-toast-native
    export class ToastHelper {
        defaultStyle: Style = {
            color: colors.white.primary,
            fontSize: 16,
            height: 140,
            borderRadius: 15,
            fontWeight: "bold",
            yOffset: 40
        }
    
        constructor() {}
    
        SHORT: number = Platform.OS === 'ios' ? 3 : 0
        LONG: number = Platform.OS === 'ios' ? 5 : 1
    
        BOTTOM: number = Platform.OS === 'ios' ? 1 : 80
        CENTER: number = Platform.OS === 'ios' ? 2 : 17
        TOP: number = Platform.OS === 'ios' ? 3 : 48
    
        success(message: string, style: Style = {}, duration: any = Toast.LONG, position: any = Toast.BOTTOM): void {
            let successStyle: Style = Object.assign(deepCopy(this.defaultStyle), style, { backgroundColor: '#5CB85C'});
            Toast.show(message, duration, position, successStyle)
        }
    
        info(message: string, style: Style = {}, duration: any = Toast.LONG, position: any = Toast.BOTTOM): void {
            let infoStyle: Style = Object.assign(deepCopy(this.defaultStyle), style, { backgroundColor: '#62B1F6'});
            Toast.show(message, duration, position, infoStyle)
        }
    
        warning(message: string, style: Style = {}, duration: any = Toast.LONG, position: any = Toast.BOTTOM): void {
            let warningStyle: Style = Object.assign(deepCopy(this.defaultStyle), style, { backgroundColor: '#F0AD4E'});
            Toast.show(message, duration, position, warningStyle)
        }
    
        error(message: string, style: Style = {}, duration: any = Toast.LONG, position: any = Toast.BOTTOM): void {
            let errorStyle: Style = Object.assign(deepCopy(this.defaultStyle), style, { backgroundColor: '#D9534F'});
            Toast.show(message, duration, position, errorStyle)
        }
    }
    
    var toastHelper = new ToastHelper()
    export default toastHelper
