### ISSUE TITLE
Font color not changing - Android - Solved

### ISSUE THREAD

**Issue by SurajMDurgad** [onemolegames/react-native-toast-native#3]
I tried to change the font colour with 'color' attribute in styles but it didn't change, other than that everything else is working fine.

**Comment by yasemincidem** [comment]
Do you have this problem which platform ? Android or iOS ?

**Comment by SurajMDurgad** [comment]
Android

On 29-Sep-2017 8:19 PM, "Yasemin Çidem" <notifications@github.com> wrote:

Do you have this problem which platform ? Android or iOS ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/onemolegames/react-native-toast-native/issues/3#issuecomment-333147370>,
or mute the thread

**Comment by yasemincidem** [comment]
You are right I realized that this is missing part on android after that you say . I will correct this wrong and update version .

**Comment by SurajMDurgad** [comment]
Thank you. 
Please do let me know when its updated.

**Comment by yasemincidem** [comment]
@SurajMDurgad i have already release new version that contains solve of problem that you mentioned .
Can you check last release please ?

**Comment by SurajMDurgad** [comment]
@yasemincidem Hey, It's working now! Amazing job. Thanks for helping me out. :tada:

**Comment by yasemincidem** [comment]
np 👍

**Comment by ZeroCool00** [comment]
@yasemincidem  is it really working ? 
`"react-native-toast-native": "^1.2.1"`
