### ISSUE TITLE
Task :react-native-toast-native:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by irondsd** [onemolegames/react-native-toast-native#30]
I'm getting this error while building the app. It doesn't happen on debug, only on  release.

Task :react-native-toast-native:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-toast-native:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2711: error: resource android:attr/fontStyle not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2712: error: resource android:attr/font not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2713: error: resource android:attr/fontWeight not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2715: error: resource android:attr/ttcIndex not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2796: error: resource android:attr/startX not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2799: error: resource android:attr/startY not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2802: error: resource android:attr/endX not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2805: error: resource android:attr/endY not found.
  /Users/irondsd/dev/cjournal/node_modules/react-native-toast-native/android/build/intermediates/res/merged/release/values/values.xml:2813: error: resource android:attr/offset not found.
  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

**Comment by gabrielhpugliese** [comment]
Did you find any workaround? This is really a blocker

**Comment by irondsd** [comment]
> Did you find any workaround? This is really a blocker

This helped me:
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
cd android
./gradlew assembleRelease -x bundleReleaseJsAndAssets

**Comment by aahmedfouad** [comment]
@irondsd getting the same error , I tried your solution but didn't work

**Comment by ABHISHEK-360** [comment]
getting the same error
This module needs to be updated or removed.

**Comment by Iamhere** [comment]
This worked for me https://github.com/facebook/react-native/issues/19239#issuecomment-502784768

**Comment by AdilKhn** [comment]
@Iamhere's link worked for me too. Thanks!

**Comment by MahadevG** [comment]
I resolve the issue by Updating the `compileSdkVersion` to 28 in build.gradle of android root.
