### ISSUE TITLE
Pod Install Fails

### ISSUE THREAD

**Issue by periabyte** [onemolegames/react-native-toast-native#32]
currently receiving an error when doing `pod install`

```
Fetching podspec for `RNToastNative` from `../node_modules/react-native-toast-native/ios`
[!] The `RNToastNative` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.`
```

**Comment by yasemincidem** [comment]
Hi @periabyte. I am trying to reproduce this issue as you said but there is no chance. It seems to be working for me. Please clarify me about the steps.

**Comment by xotahal** [comment]
Seems it is happening for react-native 0.60 and auto-linking feature

**Comment by periabyte** [comment]
It's in react native 0.60

**Comment by ventr1x** [comment]
So you close the issue with that comment and no resolution whatsoever?
Is your solution to use old react versions for this plugin?
