### ISSUE TITLE
Pod install failed

### ISSUE THREAD

**Issue by VentroArt** [onemolegames/react-native-toast-native#34]
Added library to my project.
Added next line to Podfile
Run `pod install` 

expected result:
- all pods will be installed
actual result:
[!] The `RNToastNative` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.

As far as I understand need fill `s.homepage` line in `RNToastNative.podspec` file with some url, for example url address to this git project

**Comment by ventr1x** [comment]
It basically doesn't work with never react version and the contributors don't care.
Just forget this plugin.
