### ISSUE TITLE
New version can't be compiled on Android - Error:(21, 5) error: method does not override or implement a method from a supertype 

### ISSUE THREAD

**Issue by AlmogRnD** [onemolegames/react-native-toast-native#4]
Getting the following error on Android, I just updated today. Can't build app. Here is the error 

Error:(21, 5) error: method does not override or implement a method from a supertype

Error:Execution failed for task ':react-native-toast-native:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by yasemincidem** [comment]
Which react native version you use  ?

**Comment by AlmogRnD** [comment]
I'm on "react-native": "0.48.4",

**Comment by yasemincidem** [comment]
@AlmogRnD  yes you're right. There is changes about this issue in here.They said that Android package override must be removed  in entire of RN>0.47 versions .So i have already added this statement and i released new version about my package.Can you check this last version please ?
